### ISSUE TITLE
Poor Commit Authorship

### ISSUE THREAD

**Issue by baalajimaestro** [LineageOS/android_kernel_xiaomi_violet#1]
Referencing Issue: https://github.com/LineageOS/android_device_xiaomi_violet/issues/1

Here too we can see the problem of commit authorship not given to (@GuaiYiHu) and the maintainer taking all credits to a code he never owns.

https://github.com/GuaiYiHu/android_kernel_xiaomi_sm6150/commit/11d97c37162f17c8ae37695613426437b227624

and

https://github.com/LineageOS/android_kernel_xiaomi_violet/commit/16c1081b081ac296c4ca08236436b2df6ff009b2

**Comment by baalajimaestro** [comment]
CC: @Rashed97 @luk1337

**Comment by YaroST12** [comment]
Look at the commit dates.

**Comment by luk1337** [comment]
I think this is the third time I see someone linking these two commits, can't you at least try bit harder instead of reposting old stuff?

**Comment by mikeNG** [comment]
This is not how you engage directors. If you want to engage in a conversation with the directors you email directors@lineageos.org. And you know this.
